### ISSUE TITLE
可以添加一个识别网络图片的接口嘛

### ISSUE THREAD

**Issue by Hn1993** [shlockfan/IdCardScanProject#1]
可以在ImageLoader这个接口里直接加一个识别网络图片的方法吗

**Comment by shlockfan** [comment]
在displayImage里加个判断，
if(!TextUtils.isEmpty(path)&&path.startWith("http")){
//load(path) ...... 加载网络
}else{
//load(new File(path)) ......加载本地
}

**Comment by Hn1993** [comment]
好的  谢谢了  我试下  我想的是在里面加个Flag判断   但是ImageLoader我又没有修改权限  哈哈 赞一个

**Comment by Hn1993** [comment]
我没有找到path这个参数在哪修改 。。小白请谅解。。。能不能有时间帮忙修改下

**Comment by shlockfan** [comment]
可能是我理解错了，你的网络图片是什么意思，是优图直接识别网络图片的身份证？优图接口要求的是Base64编码的图片，如果是网络图片，只能先下载下来，再转base64传给优图服务器，如果只是单纯的展示网络图片，直接用Glide加载就行了

**Comment by shlockfan** [comment]
那个ImageLoader只是配合相册选取库使用的，Glide也可以从网络url里面获取到bitmap

**Comment by Hn1993** [comment]
恩  我已经改好了  是这样的  我们的身份证照片是先传到后台   然后我从后台回去身份证信息  我已经改到先用glide加载bitmap  然后转Base64传给优图服务器了 谢了

**Comment by shlockfan** [comment]
ok
